  version: '3'
  services:
    db:
      build: ./db/
      container_name: postgres_solicitudes
      environment:
        POSTGRES_DB: db_solicitudes
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - "5434:5432"                           