version: '3'
services:
  db:
    build: ./db/
    container_name: postgres_solicitudes
    environment:
      POSTGRES_DB: db_solicitudes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    networks:
      - app_network
  api:
    build: ./API_Solicitudes/
    container_name: API_Solicitudes
    environment:
      DB_NAME: db_solicitudes
      DB_USER: admin
      DB_PORT: 5432
      DB_HOST: db  # Asegúrate de que la API se conecte usando el nombre del servicio
      DB_PASSWORD: admin
      PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/build
      - /usr/src/app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
